In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6732, 4013, 4485, 2398],
 [6732, 4013, 4485, 9513],
 [6732, 1603, 4485, 1323],
 [6824, 3068, 2427, 6323, 2977],
 [6824, 3068, 2427, 6323, 8620],
 [3297, 6732, 5721, 4485, 1167],
 [2788, 2821, 2095, 6323]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6732 4013 4485 2398]
 [   0    0    0    0 6732 4013 4485 9513]
 [   0    0    0    0 6732 1603 4485 1323]
 [   0    0    0 6824 3068 2427 6323 2977]
 [   0    0    0 6824 3068 2427 6323 8620]
 [   0    0    0 3297 6732 5721 4485 1167]
 [   0    0    0    0 2788 2821 2095 6323]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/Users/kishorkumarparoi/Desktop/ML-Project/venv/lib/python3.13/site-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step


array([[[ 0.00907264,  0.04996159,  0.0207737 ,  0.04050262,
         -0.04339631, -0.03870269,  0.04469837,  0.02074294,
         -0.02770561,  0.02006179],
        [ 0.00907264,  0.04996159,  0.0207737 ,  0.04050262,
         -0.04339631, -0.03870269,  0.04469837,  0.02074294,
         -0.02770561,  0.02006179],
        [ 0.00907264,  0.04996159,  0.0207737 ,  0.04050262,
         -0.04339631, -0.03870269,  0.04469837,  0.02074294,
         -0.02770561,  0.02006179],
        [ 0.00907264,  0.04996159,  0.0207737 ,  0.04050262,
         -0.04339631, -0.03870269,  0.04469837,  0.02074294,
         -0.02770561,  0.02006179],
        [ 0.02330733, -0.04274334, -0.01655548,  0.00685471,
         -0.02566265, -0.04207786,  0.04055256, -0.02329849,
          0.04446648,  0.00104038],
        [ 0.00669454, -0.03429031,  0.02427044,  0.03103782,
         -0.027502  ,  0.01391668,  0.0473379 ,  0.01965991,
         -0.04618746,  0.01472894],
        [-0.03786267,  0.04170695, -0.00278208, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 6732, 4013, 4485, 2398], dtype=int32)

In [17]:
model.predict(embedded_docs[0:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


array([[[ 0.00907264,  0.04996159,  0.0207737 ,  0.04050262,
         -0.04339631, -0.03870269,  0.04469837,  0.02074294,
         -0.02770561,  0.02006179],
        [ 0.00907264,  0.04996159,  0.0207737 ,  0.04050262,
         -0.04339631, -0.03870269,  0.04469837,  0.02074294,
         -0.02770561,  0.02006179],
        [ 0.00907264,  0.04996159,  0.0207737 ,  0.04050262,
         -0.04339631, -0.03870269,  0.04469837,  0.02074294,
         -0.02770561,  0.02006179],
        [ 0.00907264,  0.04996159,  0.0207737 ,  0.04050262,
         -0.04339631, -0.03870269,  0.04469837,  0.02074294,
         -0.02770561,  0.02006179],
        [ 0.02330733, -0.04274334, -0.01655548,  0.00685471,
         -0.02566265, -0.04207786,  0.04055256, -0.02329849,
          0.04446648,  0.00104038],
        [ 0.00669454, -0.03429031,  0.02427044,  0.03103782,
         -0.027502  ,  0.01391668,  0.0473379 ,  0.01965991,
         -0.04618746,  0.01472894],
        [-0.03786267,  0.04170695, -0.00278208, -0.0